### ISSUE TITLE
The plugin is incompatible with @babel/core 7

### ISSUE THREAD

**Issue by r0x0r** [riot/babel-preset-es2015-riot#27]
The error message is 
```
ERROR in ./src/frontend/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/roman.sirokov/Projects/Other/latukartta/node_modules/babel-preset-es2015-riot/index.js
    at createDescriptor (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/@babel/core/lib/config/config-chain.js:315:26)
    at /Users/roman.sirokov/Projects/Other/latukartta/node_modules/@babel/core/lib/config/config-chain.js:278:7
    at buildRootChain (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/@babel/core/lib/config/config-chain.js:118:22)
    at loadPrivatePartialConfig (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/babel-loader/lib/index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/Users/roman.sirokov/Projects/Other/latukartta/node_modules/babel-loader/lib/index.js:5:194)
    at /Users/roman.sirokov/Projects/Other/latukartta/node_modules/babel-loader/lib/index.js:5:364
 @ multi ./src/frontend/main
```

"@babel/core": "^7.1.2",
 "babel-loader": "^8.0.4",
 "babel-preset-es2015-riot": "^1.1.0",

**Comment by GianlucaGuarini** [comment]
please check also https://github.com/riot/examples/tree/gh-pages/webpack
